apiVersion: v1
kind: Service
metadata:
  name: dbcreds
  labels:
    {{- include "notejam.labels" . | nindent 4 }}
type: Opaque
data:
  username: {{ .Values.dbcreds.username | b64enc }}
  password: {{ .Values.dbcreds.password | b64enc }}